### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by haesleinhuepf** [guiwitz/DAVPy_intro#1]
Hi @guiwitz ,

awesome repository, thanks for sharing this publicly! Would you mind adding a license file so that we know under which conditions we can reuse the materials?

Thanks!

Best,
Robert

**Comment by guiwitz** [comment]
Hi @haesleinhuepf,

thanks for reminding me! Originally, I didn't put a license because I just had read some story about someone just plain stealing some teaching material and publishing a commercial book with it (a thing that can't really happen with software packages). I used to put all this sort of material under BSD-3 but then became hesitant. If you have a minute, I'd be really interested if you have an opinion on this.

**Comment by guiwitz** [comment]
Just found this relatively recent paper that addresses this question. I guess I'll go for a CC-BY license. https://arxiv.org/pdf/2202.09504.pdf

**Comment by guiwitz** [comment]
Done!

**Comment by haesleinhuepf** [comment]
Awesome thanks Guillaume! 🤓
